name: linting

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  linting:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]  # Add spaces after the colon
        version: ['3.9', '3.10']  # Correct the missing colon here

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.version }}

      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run flake8
        run: |
          flake8 app.py --count --max-line-length=88 --statistics
